import { ApiProperty } from '@nestjs/swagger';
import { Column, Entity, PrimaryGeneratedColumn } from 'typeorm';
import { Role } from '../enums';

@Entity()
export class User {
  @PrimaryGeneratedColumn()
  id: number;

  @ApiProperty({
    description: 'custom user id generated by uuid module',
  })
  @Column()
  userId: string;

  @ApiProperty({
    description: 'username of the user',
  })
  @Column()
  userName: string;

  @ApiProperty({
    description: 'email of the user',
  })
  @Column()
  email: string;

  @ApiProperty({
    description: 'hashed password',
  })
  @Column()
  password: string;

  @ApiProperty({
    description: 'User Role',
  })
  @Column({
    type: 'enum',
    enum: Role,
    default: Role.VISIONARY,
  })
  role: Role;

  @ApiProperty({
    description: 'hashed refresh token',
  })
  @Column({
    default: null,
  })
  hashedRt: string;

  @ApiProperty({
    description: 'user verification status',
  })
  @Column({
    default: false,
  })
  isVerified: boolean;
}
