export enum Industries {
  AdminSupWasteMgmtRemedSrvs = 'Admin, Support, Waste Management, and Remediation Services',
  Agriculture = 'Agriculture',
  ForestryFishingHunting = 'Forestry, Fishing, and Hunting',
  ArtsEntertainmentRecreation = 'Arts, Entertainment, and Recreation',
  BiotechnologyPharmaceuticals = 'Biotechnology and Pharmaceuticals',
  BusinessConsulting = 'Business and Consulting',
  Construction = 'Construction',
  ConsumerServices = 'Consumer Services',
  Education = 'Education',
  RealEstateProperty = 'Real Estate and Property',
  RetailEcommerce = 'Retail and E-commerce',
  TravelHospitality = 'Travel and Hospitality',
  Transportation = 'Transportation',
  WebProgrammingAppDesign = 'Web Programming, App Design, and Graphic Design',
  UIUX = 'UI/UX',
}

export enum Category {
  MobileDevelopment = 'Mobile Development',
  WebDevelopment = 'Web Development',
  FrontendDevelopment = 'Frontend Development',
  BackendDevelopment = 'Backend Development',
  FullStackDevelopment = 'Full Stack Development',
  UIUXDesign = 'UI/UX Design',
  QualityAssurance = 'Quality Assurance',
  Infrastructure = 'Infrastructure',
  CloudComputing = 'Cloud Computing',
  Cybersecurity = 'Cybersecurity',
  DataScience = 'Data Science',
  MachineLearning = 'Machine Learning',
  ArtificialIntelligence = 'Artificial Intelligence',
  Blockchain = 'Blockchain',
  SocialMediaMarketing = 'Social Media Marketing',
  ContentCreation = 'Content Creation',
}

export enum ProjectStage {
  IdeaConcept = 'Idea/Concept',
  PrototypeBenchTesting = 'Prototype/Bench Testing',
  UserTesting = 'User Testing',
  MinimumViableProduct = 'Minimum Viable Product',
  ProductMarketFit = 'Product/Market Fit',
  RevenueProducing = 'Revenue Producing',
}
